mvn install:install-file -Dfile=icelink-lib/fm.icelink.jar -DgroupId=fm.icelink -DartifactId=fm.icelink -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.vpx.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.vpx -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.callstats.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.callstats -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.audioprocessing.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.audioprocessing -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.java.sarxos.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.java.sarxos -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.android.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.android -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.java.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.java -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.openh264.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.openh264 -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.opus.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.opus -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.websync4.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.websync4 -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.xirsys.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.xirsys -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.icelink.yuv.jar -DgroupId=fm.icelink -DartifactId=fm.icelink.yuv -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.jar -DgroupId=fm.icelink -DartifactId=fm -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.websync.chat.jar -DgroupId=fm.icelink -DartifactId=fm.websync.chat -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.websync.jar -DgroupId=fm.icelink -DartifactId=fm.websync -Dversion=3.2.10 -Dpackaging=jar
mvn install:install-file -Dfile=icelink-lib/fm.websync.subscribers.jar -DgroupId=fm.icelink -DartifactId=fm.websync.subscribers -Dversion=3.2.10 -Dpackaging=jar